package org.mocchi.brand.model.client

import com.fasterxml.jackson.annotation.JsonProperty

data class ShopifyShopResponse(
    val shop: ShopifyShop
)

data class ShopifyShop(
    @JsonProperty("id") val shopifyId: Long,
    @JsonProperty("name") val name: String,
    @JsonProperty("email") val email: String,
    @JsonProperty("domain") val domain: String?,
    @JsonProperty("province") val province: String?,
    @JsonProperty("country") val country: String?,
    @JsonProperty("address1") val address1: String?,
    @JsonProperty("zip") val zip: String?,
    @JsonProperty("city") val city: String?,
    @JsonProperty("source") val source: String?,
    @JsonProperty("phone") val phone: String?,
    @JsonProperty("latitude") val latitude: Double?,
    @JsonProperty("longitude") val longitude: Double?,
    @JsonProperty("primary_locale") val primaryLocale: String?,
    @JsonProperty("address2") val address2: String?,
    @JsonProperty("created_at") val createdAt: String?,
    @JsonProperty("updated_at") val updatedAt: String?,
    @JsonProperty("country_code") val countryCode: String?,
    @JsonProperty("country_name") val countryName: String?,
    @JsonProperty("currency") val currency: String?,
    @JsonProperty("customer_email") val customerEmail: String?,
    @JsonProperty("timezone") val timezone: String?,
    @JsonProperty("iana_timezone") val ianaTimezone: String?,
    @JsonProperty("shop_owner") val shopOwner: String?,
    @JsonProperty("money_format") val moneyFormat: String?,
    @JsonProperty("money_with_currency_format") val moneyWithCurrencyFormat: String?,
    @JsonProperty("weight_unit") val weightUnit: String?,
    @JsonProperty("province_code") val provinceCode: String?,
    @JsonProperty("taxes_included") val taxesIncluded: String?,
    @JsonProperty("tax_shipping") val taxShipping: String?,
    @JsonProperty("county_taxes") val countyTaxes: String?,
    @JsonProperty("plan_display_name") val planDisplayName: String?,
    @JsonProperty("plan_name") val planName: String?,
    @JsonProperty("has_discounts") val hasDiscounts: String?,
    @JsonProperty("has_gift_cards") val hasGiftCards: String?,
    @JsonProperty("myshopify_domain") val myshopifyDomain: String?,
    @JsonProperty("google_apps_domain") val googleAppsDomain: String?,
    @JsonProperty("google_apps_login_enabled") val googleAppsLoginEnabled: String?,
    @JsonProperty("money_in_emails_format") val moneyInEmailsFormat: String?,
    @JsonProperty("money_with_currency_in_emails_format") val moneyWithCurrencyInEmailsFormat: String?,
    @JsonProperty("eligible_for_payments") val eligibleForPayments: String?,
    @JsonProperty("requires_extra_payments_agreement") val requiresExtraPaymentsAgreement: String?,
    @JsonProperty("password_enabled") val passwordEnabled: String?,
    @JsonProperty("has_storefront") val hasStorefront: String?,
    @JsonProperty("eligible_for_card_reader_giveaway") val eligibleForCardReaderGiveaway: String?,
    @JsonProperty("finances") val finances: String?,
    @JsonProperty("primary_location_id") val primaryLocationId: String?,
    @JsonProperty("cookie_consent_level") val cookieConsentLevel: String?,
    @JsonProperty("visitor_tracking_consent_preference") val visitorTrackingConsentPreference: String?,
    @JsonProperty("force_ssl") val forceSsl: String?,
    @JsonProperty("checkout_api_supported") val checkoutApiSupported: String?,
    @JsonProperty("multi_location_enabled") val multiLocationEnabled: String?,
    @JsonProperty("setup_required") val setupRequired: String?,
    @JsonProperty("pre_launch_enabled") val preLaunchEnabled: String?,
    @JsonProperty("enabled_presentment_currencies") val enabledPresentmentCurrencies: List<String>?
)
