version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: mocchi-brand
      POSTGRES_PASSWORD: mocchi-brand
      POSTGRES_DB: mocchi-brand
