db:
  url: ${DATABASE_URL:postgresql://localhost:5432/mocchi}
  username: ${JDBC_DATABASE_USERNAME:mocchi}
  password: ${JDBC_DATABASE_PASSWORD:mocchi}

shopify:
  clientId: ${API_KEY}
  clientSecret: ${API_SECRET_KEY}

stripe:
  apiKey: ${STRIPE_API_KEY}

oauth:
  serverRedirect: ${SERVER_REDIRECT_URL:http://localhost:8080}
  frontRedirect: ${FRONT_REDIRECT_URL:http://localhost:3000}

brand:
  sync:
    periodInMinutes: ${SYNC_PERIOD_TIME:10080}

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
