db:
  url: ${DATABASE_URL:postgresql://localhost:5432/mocchi}
  username: ${JDBC_DATABASE_USERNAME:mocchi}
  password: ${JDBC_DATABASE_PASSWORD:mocchi}

shopify:
  clientId: ${API_KEY}
  clientSecret: ${API_SECRET_KEY}

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
